dist: xenial
language: python
python: 3.7
services:
  - docker
branches:
  only:
    - master
stages:
  - lint
  - deploy
jobs:
  include:
    - name: lint
      stage: lint
      script:
        - >
          docker run --rm -v $(pwd):/source -w /source python:3.7-slim bash -c "
          pip install flake8;
          flake8"
    - name: deploy
      stage: deploy
      script:
        - echo "deploy"
      deploy:
        provider: pypi
        username: __token__
        password:
          secure: "pdxSBZbsogt/yOjrHoRgI7jefrLBWnjHsB9jl5rB5Imw3wsFA0qkgFXcmmKfc12nqRdqXzR4RxjzhCT2y6MbP187NRnb+Vik8LoyYbQQ19LlmkXvALrZbbev1vuM5GMTCnDFy8I1iy860F1C9lXzPLdkzmLgBqWwIbsx3F3lVposCn7woInn1hwMD8BHWgHUUoSMl/8bEPlgSklsIP+8BYUYTks+3cHf2NyGKhBu15WyqQPiH/4ViIQ4sW8+l+N1CI8rUsKsdz+zEvlaA4Rv+PtJbgCkhyf9g1lbqa0VGiLDoiBySBlsHei21Lvx9psXDlnS5vin2G2GAhlZNrM1sngcvZNk1Py6oMaABvjA+jlt+Uf1uZ/4C2xfqFGWp0nkP9v/b4N3LTiXGYpKltjL7iEhywZn4Ks4U9riVHR346kQQ5avmv2ZeRpxUjhqc1HX5TDFvlLlxf4gXBCxB3yt/MHom6hNxfbcIwEhu6DhqK8R3BI4JjKvKWEA5OK9Ifu88QZJ5uISqsjr80QLPR+x2MKqjYExjG8PpQ6ncJY/CnxyOrTWyID/+Hs1TQP5WXu0+KM1G73y5FmOzYSEC42sWQ+VBDLek94e+qDtpEnNtucLx+w1F2XK2os92Zf6kxF0BJWrUVv7Sjdob3Js97mxvCVE/mTKK6trabOs75eEHJE="
        distributions: sdist bdist_wheel
        skip_existing: true
        cleanup: false
        on:
          branch: master
