dist: xenial
language: python
python: 3.7
services:
  - docker
branches:
  only:
    - master
stages:
  - lint
  - deploy
jobs:
  include:
    - name: lint
      stage: lint
      script:
        - >
          docker run --rm -v $(pwd):/source -w /source python:3.7-slim bash -c "
          pip install flake8;
          flake8"
    - name: deploy
      stage: deploy
      script:
        - echo "deploy"
      deploy:
        provider: pypi
        username: __token__
        password:
          secure: "Zm7J4PcFLHyv7On3e8OksDCLa8VJ+Dr2f1/RsEWZhpJywaAI9va+XGowiubBzHvJYVvqGXnUHGt5Wg+QVvX2YOjpNmYm9i36M3Ab0m77Noz4j4Ug/XK7sFvTKKm869AkhCuJk3sCdmP2Z9wB8ZCmAcNJULGUDKi9RgsSrS4WGZAVE+M5ZmF9PX9LwpT1zZ1Ltb244HddWUFPn7NC5WqaRB/yS7zkpPZeYly/JP4JV7Qi9y6rcFO8Ws8cBYd3kRhXLVv5nzH7baad9jM7HidvsYQLUFZyqIOD3yjwV+TW1camQetUO5raPhoKr2elLQuGE7HMHo+GPr+3fjqSbgjdxAAeo0KA4guYfDZCk7cYsiHLnGZah0e4Wiw2RgxMs9eBkEUQbwZYsdr83K/Bc4gvMqKqwsvZW4+Gkkpf60CVXzh3WFzWhjHDJFvDV38ixkVn/Ni+dLHjKb4srHUt094ArGVvJpPr13nkkI4Gkkv/mvmmrm0enAJk9hS6YWGkOhXaHK7sBKSnmjmWOhAizAbLoCUM0qRHBFF4xByRZJZNekShwZA7iHvc+gyTYFJQke0h2ubEDlpcTm4eiBasT0X35hyp0jhVArFE2pEjWlpoS0NXlKcFgRPB+vNa2jefMgLuUpC5klwfQtmNm3T1d5lhmgyT0ro1mkGPMprLQIvXm54="
        distributions: sdist bdist_wheel
        skip_existing: true
        cleanup: false
        on:
          branch: master
